install.packages("tm")
install.packages("SnowballC")
install.packages("ggdendro")
install.packages("irlba")
install.packages("topicmodels")
install.packages("dplyr")
install.packages("syuzhet")
install.packages("lsa")
install.packages("slam")
install.packages("reshape2")
install.packages("ggplot2")
install.packages("wordcloud")
library(topicmodels)
library(tm)
library(SnowballC)
library(ggdendro)
library(irlba)
library(cluster)
library(stringr)
library(plyr)
library(wordcloud)
library(syuzhet)
library(dplyr)
library(lsa)
library(slam)
library(reshape2)
library(ggplot2)
library(wordcloud)
# set the location of the R and the other files " if you are using RStudio, you can set it from the files"
setwd ("C:/Users/Theya/Desktop/Theyab/Final data/R")
### Read in the NPS data in .csv format
asadata <- read.csv("BOOK.csv")
### remove unecessary columns
# asadata$Abstract<-NULL
# asadata$Authors<-NULL
# asadata$Authors.Full.Names<-NULL
# asadata$Beginning.Page<-NULL
# asadata$Book.Series.Subtitle<-NULL
# asadata$Book.Series.Title<-NULL
# asadata$Cited.Patent<-NULL
# asadata$Cited.Reference.Count<-NULL
# asadata$Cited.References<-NULL
# asadata$City.of.Publisher<-NULL
# asadata$Conference.Dates<-NULL
# asadata$Conference.Host<-NULL
# asadata$Conference.Location<-NULL
# asadata$Conference.Sponsors<-NULL
# asadata$Conference.Title<-NULL
# asadata$DOI<-NULL
# asadata$Email.Addresses<-NULL
# asadata$Editors<-NULL
# asadata$Ending.Page<-NULL
# asadata$File.Type<-NULL
# asadata$Funding.Agency.and.Grant.Number<-NULL
# asadata$Funding.Text<-NULL
# asadata$ISBN<-NULL
# asadata$ISI.Document.Delivery.Number<-NULL
# asadata$ISSN<-NULL
# asadata$Issue<-NULL
# asadata$Journal.Name.Abbreviated.ISO<-NULL
# asadata$Journal.Name.Abbreviated<-NULL
# asadata$Journal.Title.Full<-NULL
# asadata$Language<-NULL
# asadata$New.Article.Number<-NULL
# asadata$New.ISI.Keywords<-NULL
# asadata$Number.of.Pages<-NULL
# asadata$Part.Number<-NULL
# asadata$Publication.Date<-NULL
# asadata$Publication.Type<-NULL
# #asadata$Publication.Year<-NULL
# asadata$Publisher.Address<-NULL
# asadata$Publisher.Web.Address<-NULL
# asadata$Reprint.Address<-NULL
# asadata$Research.Addresses<-NULL
# asadata$Research.Field<-NULL
# asadata$Researcher.ID<-NULL
# asadata$Special.Issue<-NULL
# asadata$Subject.Category<-NULL
# asadata$Supplement<-NULL
# asadata$Times.Cited<-NULL
# asadata$Title<-NULL
# #asadata$Total.Times.Cited<-NULL
# #asadata$Unique.ID<-NULL
# asadata$Version.Number<-NULL
# asadata$Volume<-NULL
# asadata$EI<-NULL
# asadata$RI<-NULL
# asadata$OI<-NULL
# asadata$PM<-NULL
# asadata$CA<-NULL
# asadata$U1<-NULL
# asadata$U2<-NULL
# asadata$File.Name<-NULL
# asadata$Cite.Me.As<-NULL
# 
# asadata$ID<- (1:nrow(asadata))
### Remove rows where Document Type is not Article
asadata<-subset(asadata,asadata$Document.Type=="Article")
asadata$Original<-gsub("\\."," ",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("\\-"," ",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("\\_"," ",asadata$Original,ignore.case = TRUE)
#asadata$Original<-gsub("\\)"," ",asadata$Original,ignore.case = TRUE)
#asadata$Original<-gsub("\\("," ",asadata$Original,ignore.case = TRUE)


asadata$Original<-gsub("MSC 68Q32"," ",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("MSC 62G08"," ",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("MSC 62G20"," ",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("60F10"," ",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("60G51"," ",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("60G57"," ",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("60K15"," ",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("60K99"," ",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("62C99"," ",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("62F03"," ",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("62F05"," ",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("62F15"," ",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("62F40"," ",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("62G05"," ",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("62G07"," ",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("62G08"," ",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("62G09"," ",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("62G10"," ",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("62G15"," ",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("62G20"," ",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("62G30"," ",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("62G32"," ",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("62G35"," ",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("62H05"," ",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("62H12"," ",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("62H15"," ",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("62H30"," ",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("62H99"," ",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("62J02"," ",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("62J12"," ",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("62L99"," ",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("62M05"," ",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("62M10"," ",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("62M99"," ",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("62N01"," ",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("62N02"," ",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("62P10"," ",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("62P30"," ",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("94A12"," ",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("94A17"," ",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("94A17"," ",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("62E10"," ",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("62E17"," ",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("62E20"," ",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("62G99"," ",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("62L05"," ",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Primary:"," ",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Secondary:"," ",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("\\s+"," ",asadata$Original,ignore.case = TRUE)
###Similar word replacement
asadata$Original<-gsub("*ally","al",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*ates","ate",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*ators","ator",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*bases","base",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*bjects","bject",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*cards","card",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*chains","chain",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*charts","chart",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*ches","ch",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*codes","code",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*controls","control",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*counts","count",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*ents","ent",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*fiers","fier",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*gales","gale",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*graphs","graph",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*groups","group",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*holds","hold",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*hoods","hood",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*ings","ing",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*ints","int",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*isms","ism",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*isons","ison",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*ities","ity",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*ives","ive",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*kers","ker",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*liers","lier",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*lines","line",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*matics","matic",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*means","mean",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*models","model",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*modes","mode",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*nals","nal",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*nces","nce",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*overs","over",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*pairs","pair",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*phics","phic",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*plots","plot",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*points","point",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*pounds","pound",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*puts","put",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*sets","set",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*sions","ssion",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*sters","ster",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*stics","stic",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*tants","tant",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*tests","test",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*times","time",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*tions","tion",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*tools","tool",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*tours","tour",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*trics","tric",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*ures","ure",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*uters","uter",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*widths","width",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("*works","work",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("aberrant","Aberration",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("ABILITIES","ability",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("absolutely","absolute",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("accelerate","Accelerated",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Adaptation","adaptive",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Adaption","adaptive",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("adaptivity","adaptive",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Akaike's","akaike",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("algorithms","algorithm",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("ALTERNATING","alternative",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("alternatives","alternative",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("analyses","analysis",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Angles","Angle",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("animals","animal",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("approximations","approximation",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("arrays","array",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("arrivals","arrival",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("assets","asset",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("asymptotically","Asymptotic",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Asymptotics","Asymptotic",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Attribute","Attributes",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("auto correlation","autocorrelation",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("averages","average",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("balls","ball",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("bands","band",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Bayesians","Bayesian",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("blocks","block",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("boundaries","boundary",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Bounds","Bound",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("brands","brand",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("breaks","break",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("bridges","bridg",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("categories","category",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("causes","cause",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("cells","cell",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("chain monte carlo","markov chain monte carlo",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("changepoint","change point",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("changes","change",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("checks","check",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("classes","class",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("closed","close",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("co variate","covariate",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("components","component",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Componentwise","Component wise",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("concepts","concept",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("consumers","consumer",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("copulas","copula",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("costs","cost",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("cross over","crossover",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("contrasts","contrast",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("curves","curve",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Cycles","cycle",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("decisions","decision",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("defaults","default",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("defects","defect",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Degrees","Degree",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("densities","density",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("depths","depth",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Derivatives","Derivative",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("designs","design",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("diagrams","diagram",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("diffusions","diffusion",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("effects","effect",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("factors","factor",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("fitting","fit",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("fields","field",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Goodness Of Fit Test","Goodness Of Fit",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("equations","equation",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("errors","error",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("estimations","estimation",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("estimators","estimator",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("estimator","estimation",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("experiments","experiment",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("families","family",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("forecasts","forecasting",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("heteroscedasticity","heterogeneity",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("hypotheses ","hypothesis",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("integrals","integral",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("interiorpoint","interior point",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("intervals","interval",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("invariants","invariant",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("items","item",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Jumps","Jump",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("kernels","kernel",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("knots","knot",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("languages","language",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("leastsquares","least squares",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("levels","level",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("limits","limit",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("machines","machine",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("manifolds","manifold",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("margins","margin",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("markets","market",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("markov markov chain monte carlo","markov chain monte carlo",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("maximumlikelihood","maximum likelihood",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("mcmc","markov chain monte carlo",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("metaanalysis","meta analysis",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Methods","Method",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("mixtures","mixture",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("montecarlo","monte carlo",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("negatives","negative",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("neighbors","neighbor",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("noises","noise",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("nonparametrics","nonparametric",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("normals","normal",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("numbers","number",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("outcomes","outcome",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("outlier","outliers",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("p values","p value",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("packages","package",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("parameters","parameter",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("paths","path",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Patterns","Pattern",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Pearsons","Pearson",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Pharmacokinetics","Pharmacokinetic",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("phases","phase",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("plans","plan",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("plants","plant",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("pointwise","point wise",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("policies","policy",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("polynomials","polynomial",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Polytopes","Polytope",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("populations","population",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("portfolios","portfolio",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("potentials","potential",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("predictors","predictor",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("prices","price",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Principles","Principle",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Priors","Prior",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("probabilities","probability",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("problems","problem",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("PROCESSES","PROCESS",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("PRODUCTs","PRODUCT",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("profiles","profile",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("programs","program",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("quantiles","quantile",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("ranges","range",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Ranks","Rank",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("rates","rate",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("ratios","ratio",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("records","record",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("regions","region",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("regressions","regression",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("reports","report",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("residuals","residual",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("resources","resource",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("responses","response",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("results","result",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Returns","Return",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("risks","risk",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Rivers","River",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("robustness","robust",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("roots","root",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Rules","Rule",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("runs","run",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("samples","sample",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Scales","Scale",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("schemes","scheme",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("schools","school",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("scores","score",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("seeds","seed",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("selections","selection ",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("selectors","selector",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("semi parametric","semiparametric",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("sensors","sensor",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("services","service",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("shapes","shape",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Shifts","Shift",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Shocks","Shock",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("simples","simple",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("sizes","size",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("skills","skill",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("slopes","slope",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("smoothers","smoother",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("smoother","smoothing",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("sources","source",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("spaces","space",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("spatio temporal","spatiotemporal",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("spheres","sphere",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("splines","spline",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("splits","split",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("squared","square",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Squares","Square",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("standards","standard",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("statistical","statistics",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("streams","stream",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("studies","study",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("surfaces","surface",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Surveys","Survey",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Systems","System",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("tables","table",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("tails","tail",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("techniques","technique",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("terms","term",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("timeseries","time series",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("totals","total",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("traces","trace",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("traits","trait",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("transects","transect",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("transfers","transfer",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("transforms","transform",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Transformations","Transformation",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("trees","tree",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Trends","Trend",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("trials","trial",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("types","type",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("units","unit",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("values","value",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("variables","variable",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("vectors","vector",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("wages","wage",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("wavelets","wavelet",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("ways","way",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("weights","weight",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("windows","window",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("winds","wind",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("zeros","zero",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("zones","zone",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("bandwidth selection","bandwidth",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("binary data","binary",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("bootstrapping","bootstrap",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("cluster analysis","clustering",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("regions","region",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("convergence rate","convergence",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("optimal design","optimality",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("factorials","factorial",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("fractional factorial","fractional factorial design",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Fractional Factorial Design Design","Fractional Factorial Design",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("functional data analysis","functional data",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("gene expression data","gene expression",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("gibbs sampling","gibbs sampler",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("heteroskedasticity","heterogeneity",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("hierarchical modeling","hierarchical model",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("hypothesis","hypothesis testing",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Hypothesis Testing Testing","hypothesis testing",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Hypothesis Testing Test","hypothesis testing",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Hastings","Hasting",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("image analysis","image processing",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("information criteria","information criterion",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("kaplan meier estimator","kaplan meier",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("kernel density estimation"," kernel method",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("kernel density estimator","kernel method",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("kernel estimator","kernel estimation",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("kernel regression","kernel method",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("kernel smoothing","kernel method",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("likelihood ratio test","likelihood ratio",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("longitudinal data analysis","longitudinal data",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Latent Variable Model","Latent Variable",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("local polynomial regression method","local polynomial regression",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("m estimator","m estimation",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("metropolis hasting algorithm","metropolis hasting",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("metropolis algorithm","metropolis hasting",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("missing at random","missing data",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("mixed model","mixed effects model",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("mixture model","mixture",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("modeling","model",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("monte carlo method","monte carlo",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("monte carlo simulation","monte carlo",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("mulitple comparison","multiple comparisons",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("multilevel modeling","multilevel model",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("multivariate analysis","multivariate",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Maximum Likelihood Estimate","Maximum Likelihood Estimation",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Measurement Error Model","Measurement Error",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("negative binomial distribution","negative binomial",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("nonlinear regression","nonlinear model",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("nonparametric estimation","nonparametric",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("nonparametric test","nonparametric",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("principal component","principal component analysis",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("principal component analysis analysis","principal component analysis",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("proportional hazards","proportional hazards model",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("proportional hazards model model","proportional hazards model",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("quality control","statistical process control",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("regression analysis","regression",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("regression model","regression",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("partially linear model","partial linear model",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("reversible jump markov chain monte carlo","reversible jump",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("R Package","R",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("R program","R",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("R programming","R",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("R software","R",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("state space model","state space",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("survival","survival analysis",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("survival data","survival analysis",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("survival analysis analysis","survival analysis",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("survival analysis data","survival analysis",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("truncation","truncated data",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Random Effect Model","Random Effect",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Sensitivity Analysis","Sensitivity",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Statistics Process Control","Statistical Process Control",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Transformation Model","Transformation",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Acceleratedd","Accelerated",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Accelerated failure time model","Accelerated failure time",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("kernel estimate","Kernel estimation",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Mixed effect model","Mixed effects model",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("State space Method","State space",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("nonparametric","non parametric",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("markov chain monte carlo (markov chain monte carlo) simulation","markov chain monte carlo",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("markov chain monte carlo (markov chain monte carlo)","markov chain monte carlo",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("markov chain monte carlo algorithm","markov chain monte carlo",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("RJ markov chain monte carlo","Reversible Jump markov chain monte carlo",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("RJmarkov chain monte carlo","Reversible Jump markov chain monte carlo",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("item response theory (IRT)","IRT",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("item response theory model","IRT",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("multilevel IRT","multileve IRT",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("multidimensional IRT","multidimensional IRT",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("IRT model","IRT",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("item response theory model fit","IRT",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("National Assessment of Educational Progress (NAEP)","NAEP",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("National Assessment of Educational Progress","NAEP",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("restricted maximum likelihood (REML)","REML",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("restricted maximum likelihood","REML",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Aerosol optical depth (AOD)","AOD",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Aerosol optical depth","AOD",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Ordinary differential equation (ODE)","ODE",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Ordinary differential equation","ODE",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("AVERAGE RUN LENGTH (ARL)","ARL",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("AVERAGE RUN LENGTH","ARL",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Fixed Rank Kriging (FRK)","FRK",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Fixed Rank Kriging","FRK",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Smoothly clipped absolute deviation (SCAD)","SCAD",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Smoothly clipped absolute deviation","SCAD",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Stein's unbiased risk estimate (SURE)","SURE",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Stein's unbiased risk estimate","SURE",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Akaike information criterion (AIC)","AIC",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("akaike AIC","AIC",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("akaike criteria","AIC",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Akaike criterion","AIC",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Akaike information criterion","AIC",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("alternate conditioning expectation (ACE)","ACE",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("alternative CONDITIONAL EXPECTATION (ACE) ALGORITHM","ACE",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Analysis of covariance (ANCOVA)","ANCOVA",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Analysis of covariance","ANCOVA",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Area under the curve (AUC)","AUC",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Area under the curve","AUC",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Classification and Regression tree (CART)","CART",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Classification and Regression tree","CART",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Conditional autoregressive (CAR) model","CAR",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Conditional autoregressive model","CAR",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("conditional autoregressive prior","CAR",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Conditional autoregressive","CAR",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("conditional autoregression","CAR",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("CAR model","CAR",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("correspondence analysis (CA)","correspondence analysis",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("cumulative sum (CUSUM)","CUSUM",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("cumulative sum chart","CUSUM",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("cumulative sums","CUSUM",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("cumulative sum","CUSUM",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("CUSUM chart","CUSUM",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("CUSUM MONITORING","CUSUM",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("cusum process","CUSUM",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("CUSUM test","CUSUM",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("CUSUMS","CUSUM",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("False discovery rate (FDR)","FDR",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("False discovery rate","FDR",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("familywise","family wise",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Family wise error rate (FWER) control","FWER",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Family wise error rate","FWER",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Family wise error","FWER",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Family wise","FWER",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("functional magnetic resonance imaging (fMRI)","FMRI",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("functional magnetic resonance imaging","FMRI",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("generalized additive model (GAM)","GAM",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("generalized additive model","GAM",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("generalized estimating equation (GEE)","GEE",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("generalized estimating equation","GEE",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("weighted GEEs","weighted GEE",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("generalized linear mixed effects model (GLMM)","GLMM",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("generalized linear mixed effects model","GLMM",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("generalized linear mixed effect model","GLMM",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("generalized method of moment (GMM)","GMM",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("generalized method of moment","GMM",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Genome wide association study (GWAS)","GWAS",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Genome wide association study","GWAS",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Geographic Information System (GIS)","GIS",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Geographic Information System","GIS",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("LASSO (Least Absolute Shrinkage and Selection Operator)","LASSO",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Least absolute shrinkage and selection operator (Lasso)","LASSO",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Least absolute shrinkage and selection operator","LASSO",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Linear discriminant analysis (LDA)","LDA",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Linear discriminant analysis","LDA",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Linear mixed effects model (LMM)","LMM",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Linear mixed effects model","LMM",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("linear mixed effect model","LMM",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("linear mixing model","LMM",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("marginal maximum likelihood (MML) estimation","MML",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("marginal maximum likelihood","MML",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("MML estimation","MML",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Markov random field (MRF)","MRF",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Markov random field mode","MRF",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Markov random field","MRF",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Maximum likelihood estimation (MLE)","Maximum likelihood estimation",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("mean integrated square error (MISE)","MISE",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("mean integrated square error","MISE",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("mean integrated squarred error","MISE",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("principal component analysis (PCA) projection","PCA",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("principal component analysis regression","PCA",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("principal component analysis","PCA",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("reproducing kernel Hilbert space (RKHS)","RKHS",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("reproducing kernel Hilbert space","RKHS",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("singular value decomposition (SVD)","SVD",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("SINGULAR VALUE DECOMPOSITION","SVD",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("sliced inverse regression (SIR)","SIR",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("sliced inverse regression","SIR",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("sliced average variance estimation (SAVE)","SAVE",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("sliced average variance estimation","SAVE",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Threshold autoregressive (TAR)","TAR",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("threshold autoregressive model","TAR",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("threshold autoregressive process","TAR",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Vector autoregressive (VAR) process","VAR",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("vector autoregressive model","VAR",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Vector autoregressive process","VAR",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("ANALYSIS OF VARIANCE estimation","ANOVA",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("ANALYSIS OF VARIANCE MODEL","ANOVA",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Analysis of variance","ANOVA",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("Goodness of fit Method","goodness of fit",asadata$Original,ignore.case = TRUE)
asadata$Original<-gsub("goodness of fittest","goodness of fit",asadata$Original,ignore.case = TRUE)

asadata$Original<-gsub("\\s+"," ",asadata$Original,ignore.case = TRUE)




write.csv(asadata,file="TheyabKW1.csv")